fos_ck_editor:
    default_config: default
    configs:
        default:
            toolbar:
                - { name: "styles", items: ["Format", "Font", "FontSize"] }
                - { name: "basicstyles", items: ["Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript", "-", "RemoveFormat"] }
                - { name: "paragraph", items: ["NumberedList", "BulletedList", "-", "Outdent", "Indent", "-", "Blockquote", "-", "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"] }
                - { name: "links", items: ["Link", "Unlink"] }
                - { name: "insert", items: ["Image", "Table", "HorizontalRule", "SpecialChar"] }
                - { name: "tools", items: ["Maximize", "Source"] }
            filebrowserBrowseRoute: admin
            filebrowserUploadRoute: admin
            filebrowserUploadMethod: form
